### ISSUE TITLE
Helm Chart for runtime-class-manager

### ISSUE THREAD

**Issue by voigt** [spinkube/runtime-class-manager#47]
A Helm Chart should be provided to simplify the installation of runtime-class-manager.

As spinkube will eventually depend on it, we should add reasonable defaults, as the rcm helm-chart will be used as a Helm dependency.

I assume that we can use a lot of inspiration from the existing Kwasm helm chart.

**Comment by flavio** [comment]
I can take this one. Are you fine with me copying and adapting the helm charts we used to have inside of the kwasm project?

**Comment by vdice** [comment]
Added in https://github.com/spinkube/runtime-class-manager/pull/204.
